### ISSUE TITLE
Document that SystemDistributedLock does not work on Linux

### ISSUE THREAD

**Issue by hahn-kev** [madelson/DistributedLock#52]
When running on linux you will get this exception when trying to aquire the lock
```
System.PlatformNotSupportedException : Access Control List (ACL) APIs are part of resource management on Windows
 and are not supported on this platform.
  Stack Trace:
     at System.Security.AccessControl.ObjectSecurity..ctor()
   at System.Security.AccessControl.CommonObjectSecurity..ctor(Boolean isContainer)
   at System.Security.AccessControl.NativeObjectSecurity..ctor(Boolean isContainer, ResourceType resourceType)
   at System.Security.AccessControl.EventWaitHandleSecurity..ctor()
   at Medallion.Threading.SystemDistributedLock.CreateEvent()
   at Medallion.Threading.SystemDistributedLock.InternalTryAcquireAsync(Int32 timeoutMillis, CancellationToken canc
ellationToken)

```

I'm still determining a workaround, I only use this for unit tests so I'll probably fall back to a process level lock.

**Comment by madelson** [comment]
@hahn-kev unfortunately global event handles are windows-only.

DistributedLock 2.0 will also offer file-based locks as a cross-platform alternative for system-wide locking. I can publish a prerelease of that module if you'd like to give it a try.

**Comment by hahn-kev** [comment]
Ahh ok, I didn't realize that, maybe could that be mentioned in the documentation? I assumed it was cross platform since the other locks are.

I made a simple alternative for testing that's in memory only and that works for my use case, so I don't need the pre release, thank you!
